# Generated by Django 4.2.4 on 2023-09-11 00:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0004_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="comment",
            field=models.CharField(
                default=datetime.datetime(
                    2023, 9, 11, 0, 41, 10, 147426, tzinfo=datetime.timezone.utc
                ),
                max_length=140,
            ),
            preserve_default=False,
        ),
    ]
